name: Build PxWeb

on:
  workflow_dispatch:    # manual trigger from GitHub UI
  #push:
  #  branches: [ main ]  # optional: build on pushes to main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore packages
      run: nuget restore PCAxis.PX-Web.sln

    - name: Build the application
      #run: msbuild /p:Configuration=Release
      run: msbuild PXWeb/PXWeb.csproj /t:Build /p:Configuration=Release /p:OutputPath=${{ github.workspace }}\artifacts\PxWeb

    - name: Print current folder path with PowerShell
      shell: pwsh
      run: |
          Write-Output "Current folder path is: $PWD"
          Write-Output "Or using Get-Location: $(Get-Location)"          
          get-childitem
    
    - name: Prepare deploy folder
      shell: pwsh
      run: |
        # Create a staging folder that mimics an IIS deployable site
        New-Item -ItemType Directory -Force -Path deploy
        # Copy web root contents (adjust if project path differs)
        # Assuming main web project folder is PxWeb
        Copy-Item -Path "PxWeb.Test\*" -Destination "deploy" -Recurse -Force
        # Ensure bin contains Release outputs
        Remove-Item -Path "deploy\bin" -Recurse -Force -ErrorAction Ignore
        New-Item -ItemType Directory -Force -Path "deploy\bin"
        Copy-Item -Path "PxWeb.Test\bin\Release\*" -Destination "deploy\bin" -Recurse -Force
        # Optional: remove local dev files not needed in deployment
        Remove-Item -Path "deploy\.vs","deploy\.gitignore" -Recurse -Force -ErrorAction Ignore

    - name: Zip deployable package
      shell: pwsh
      run: |
        #Compress-Archive -Path "deploy\*" -DestinationPath "PxWeb_Release.zip"
        Compress-Archive -Path "PxWeb.Test\*" -DestinationPath "PxWeb_Release.zip"
        #Compress-Archive -Path "PxWeb.Test\bin\Release\*" -DestinationPath "PxWeb_Release.zip"
        #Compress-Archive -Path "publish_output/*" -DestinationPath "PxWeb_Release.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PxWeb_Release
        path: PxWeb_Release.zip
        if-no-files-found: error
